# Generated by Django 5.2.4 on 2026-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', '💼 Work'), ('study', '📚 Study'), ('personal', '🏠 Personal'), ('shopping', '🛒 Shopping'), ('health', '💪 Health'), ('other', '📌 Other')], default='other', max_length=20),
        ),
    ]
